config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'orders#new'

  get 'om',       to: 'pages#info', as: :info
  get 'hjalp',    to: 'pages#help', as: :help
  get 'integritetspolicy', to: 'pages#integritetspolicy', as: :integritetspolicy

  get 'dev-card', to: 'pages#dev_card', as: :dev_card
  get 'card-private-standard', to: 'pages#card_private_standard', as: :card_private_standard
  get 'card-private-xmas', to: 'pages#card_private_xmas', as: :card_private_xmas
  get 'card-business-standard', to: 'pages#card_business_standard', as: :card_business_standard
  get 'card-business-standard-en', to: 'pages#card_business_standard_en', as: :card_business_standard_en
  get 'card-business-xmas', to: 'pages#card_business_xmas', as: :card_business_xmas
  get 'dev-design', to: 'pages#dev_design', as: :dev_design

  get 'sms-order/jAuEhzn193', to: 'sms#new'
  get 'sms-order/s87sMxefrw', to: 'sms#new_xmas'
  get 'sms-order/Ksa812jDjb', to: 'sms#new_small'
  get 'sms-order/f12bnffG1A', to: 'sms#new_xmas_small'

  resources :giftcards

  get 'foretag2', to: 'giftcards#foretag'

  namespace :company, path: 'foretag' do
    get '/', to: 'orders#new'
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]
  end

  resources :persons, only: [:create]

  scope path_names: { new: 'skapa', edit: 'redigera' } do
    resources :cards, :digital_cards, :analog_cards, path: 'gavobevis', except: [:new] do
      get 'bekrafta', action: :confirmation, on: :member, as: :confirmation
      get 'forhandsgranska', action: :preview, on: :member, as: :preview
    end

    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]

    resource :cart, path: 'varukorg', only: [:show, :update]
    resource :checkout, path: 'checkout', path_names: { new: '' }, only: [:new] do
      get 'complete', action: :complete, as: :complete
      get 'swish', action: :swish, as: :swish
      post 'charge', action: :charge, as: :charge
      get 'swish_payment_status'
    end

    scope module: 'customer' do
      resources :customers, path: 'kund' do
        resources :cards, path: 'gavobevis', only: [:edit, :update] do
          get 'forhandsgranska', action: :preview, on: :member, as: :preview
        end
      end
    end
  end

  ##########################################
  # Service callbacks
  ##########################################
  scope '/callbacks' do
    post 'stripe', to: 'callbacks#stripe'
    post 'swish', to: 'callbacks#swish'
  end

  ##########################################
  # Sidekiq
  ##########################################
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  token      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Customer < ActiveRecord::Base
  before_create :generate_token

  default_scope { where(arel_table[:created_at].gt(Time.now - 48.hour)) }

  validates_format_of :email,
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      :allow_blank => false

  validate :customer_email

  def donor
    Donor.where(email: email).joins(:order).merge(Order.completed).order(created_at: :desc).limit(1).take
  end

  def orders
    Order.completed.joins(:donor).where(donors: { email: email }).order(created_at: :desc)
  end

  def find_card(token)
    Card.unsent.where(token: token).joins(:order).merge(orders).take!
  end

  private

  def customer_email
    errors.add(:email, 'is not a customer') unless donor
  end

  def generate_token
    self.token = loop do
      token = SecureRandom.urlsafe_base64(16)
      break token unless self.class.exists?(token: token)
    end
  end
end

app/controllers/customer/cards_controller.rb
class Customer::CardsController < ApplicationController
  def edit
    @customer = Customer.find_by!(token: params[:customer_id])
    @card = @customer.find_card(params[:id])
    @card.send_at ||= Date.today
  end

  def update
    @customer = Customer.find_by!(token: params[:customer_id])
    @card = @customer.find_card(params[:id])

    if @card.update_attributes(card_params)
      @card.save
      @card.reschedule!

      if card_params[:send_to_donor] && @customer.email["@example.com"] # system-generated email
        @card.order.donor.update_attributes!(email: card_params[:receiver])
        @customer.update_attributes!(email: card_params[:receiver])
      end

      redirect_to customer_url(@customer.token)
    else
      render 'edit'
    end
  end

  private

  def card_params
    params.require(:card).permit(
      :text, :receiver, :send_at,
      :send_to_donor, :type, :subtype
    )
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def index
    @customer = Customer.new
  end

  def show
    @customer = Customer.find_by!(token: params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to :customers, error: 'Länken är ogiltig. Försök igen genom att begära utt ett nytt.'
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      CustomerMailer.delay.token(@customer.id)
      redirect_to :customers, notice: 'Vi har skickat länken till din e-postadress.'
    else
      render :index
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:email)
  end
end

app/views/customer/customers/_form.html.erb
<%= form_for(customer, :html => { :class => 'your-orders' }, :data => {'parsley-validate' => '', 'rr-name' => 'customer-form' }) do |f| %>
  <div>
    <%= f.label :email, 'Din e-post' %>
    <%= f.email_field(:email, class: 'your-orders__email', data: {'parsley-type' => 'email', 'parsley-required' => '', 'parsley-required-message' => 'Fyll i din e-postadress'}) %>
  </div>

  <%= f.submit 'Skicka', class: 'your-orders__submit' %>
<% end %>

app/views/customer/customers/_orders_intro.html.erb
 <h1 class="page__title">Skapa ditt gåvobevis</h1>
   <p class="blue">
   Hej <%= @customer.donor.full_name %>!
   </p>
   <p class="blue">
   Stort tack för att du har räddat och förändrat liv! Nu ska du skapa ditt gåvobevis. Ett kvitto samt bekräftelse på gåvan har skickats till din e-post.
   </p>
   <p class="blue">Nedan ser du en lista på de gåvobevis som du har gett bort.</p>
   <p class="blue">Tryckta gåvobevis skickas med post direkt hem till dig. För digitala gåvobevis ska du nu välja mottagare och skriva en hälsning.</p>
   <p class="blue">Har du några frågor kring din beställning hör av dig till <a href="mailto:info@wateraid.se">info@wateraid.se</a>.</p>
   <p class="blue">
      Stort tack,<br>
      WaterAid
    </p>

app/views/customer/customers/_orders_intro_company.html.erb
 <h1 class="page__title">Skapa ert gåvobevis</h1>
   <p class="blue">
   Hej <%= @customer.donor.full_name %>!</p>
   <p class="blue">
   Stort tack för att ni har räddat och förändrat liv! Ett kvitto samt bekräftelse på gåvan har skickats till din e-post.
   </p>
   <p class="blue">Nedan ser du en lista på de gåvobevis som ni har gett bort.</p>
   <p class="blue">Nu ska du välja mottagare för ditt digitala gåvobevis och skriva en hälsning.</p>
   <p class="blue">Klicka här för att se dina <a href="https://gavoshop.wateraid.se/kund" target="_blank">tidigare beställningar</a>.</p>
   <p class="blue">Har du några frågor så hör av dig till <a href="mailto:infocorporate@wateraid.se">infocorporate@wateraid.se</a>.</p>
   <p class="blue">
      Stort tack,<br>
      WaterAid
    </p>

app/views/customer/customers/_orders_intro_sms.html.erb
   <h1 class="page__title">Skapa ditt gåvobevis</h1>
   <hr>
   <p class="blue">
   Hej!
   </p>
   <p class="blue">
     Stort tack för att du har beställt ett gåvobevis. Din gåva kommer att ge människor rent vatten och förändra liv.
   </p>
   <p class="blue">
     Nedan skapar du ditt gåvobevis genom att fylla i mottagare och skriver en hälsning. Om du vill beställa fler gåvobevis gå in på <a href="https://gavoshop.wateraid.se/">https://gavoshop.wateraid.se/</a>.
   </p>
   <p class="blue">
     Om du har frågor så hör av dig till <a href="mailto:info@wateraid.se">info@wateraid.se</a>.
   </p>
   <p class="blue">
     Tack,<br>
     WaterAid
   </p>

app/views/customer/customers/index.html.erb
<% title "Dina beställningar" %>
<% description "Fyll i din e-postadress i formuläret nedan så skickar vi dig en länk som fungerar i 24 timmar. Där kan du se alla dina tidigare beställningar och har möjlighet att redigera de digitala kort som ännu ej skickats ut." %>

<main class="page" role="main">
  <article>
    <h1 class="page__title">Dina beställ&shy;ningar</h1>

    <hr>

    <p class="t-lead">Har du beställt från oss tidigare?</p>
    <p>Fyll i din e-postadress i formuläret nedan så skickar vi dig en länk som fungerar i 24 timmar.</p>

    <p>Där kan du se alla dina tidigare beställningar och har möjlighet att redigera de digitala kort som ännu ej skickats ut.</p>

    <%= render partial: 'form', locals: {customer: @customer} %>
  </article>
</main>

app/views/customer/customers/show.html.erb
<% html_classes "card-bg about" %>
<% title "Skapa dina gåvobevis" %>

<main class="page" role="main">
  <article>
    <div class="page__intro">
    <% if @customer.orders.first.payment_type == 'sms' %>
      <%= render "orders_intro_sms" %>
    <% elsif @customer.orders.first.donor.donor_type == "company" %>
      <%= render "orders_intro_company" %>
    <% else %>
      <%= render "orders_intro" %>
    <% end %>
    </div>

    <div class="page__orders">
      <table class="orders order__items">
      <tbody>
        <% @customer.orders.each do |order| %>
          <tr class="orders__caption">
            <th colspan="5">
              <h3>#<%= order.id %> <small><% order.created_at %> / Totalt: <%= order.total %> kr</small></h3>
            </th>
          </tr>
          <tr>
            <th>Typ</th>
            <th>Summa</th>
            <th></th>
          </tr>

          <% order.cards.each do |card| %>
            <tr class="order__item">
              <td class="order__item__type">
                <% if card.class.model_name == "Extra" %>
                  Extra gåva
                <% else %>
                  <%= card_title(card) %>

                  <small>
                  <% if card.type == 'DigitalCard' %>
                      <% if card.receiver.blank? %>
                        <%= image_tag 'icons/new.svg', data: { 'fallback': image_path('icons/new.png') } %>
                        Lägg in innehåll och välj datum.
                      <% else %>
                        <% if card.sent_at %>
                          <%= image_tag 'icons/check.svg', data: { 'fallback': image_path('icons/check.png') } %>
                          Skickat
                          <%= card.sent_at.strftime('%Y-%m-%d') %>
                        <% else %>
                          <%= image_tag 'icons/clock.svg', data: { 'fallback': image_path('icons/clock.png') } %>
                          Skickas

                          <% if card.send_at == Date.today %>
                            omgående
                          <% else %>
                            <%= card.send_at.strftime('%Y-%m-%d') %>
                          <% end %>
                        <% end %>

                        till

                        <% if card.send_to_donor == true %>
                          dig själv.
                        <% else %>
                          <%= card.receiver %>.
                        <% end %>
                      <% end %>
                  <% else %>
                    Skickas inom fyra arbetsdagar från orderdatumet.
                  <% end %>
                  </small>
                <% end %>
              </td>
              <td class="order__item__price"><%= card.price %> kr</td>
              <td class="order__item__actions">
                <% if card.type == 'DigitalCard' %>
                  <% if card.receiver.blank? %>
                    <%= link_to('skapa gåvobevis', edit_customer_card_path(@customer.token, card.token), class: 'button-pill button-pill--action') unless card.sent_at %>
                  <% else %>
                    <% if card.sent_at %>
                      <%= link_to('visa', card_path(card.token), class: 'button-pill', target: '_blank') %>
                    <% else %>
                      <%= link_to('förhandsvisa / ladda ner', card_path(card.token, :preview => "true", :customer => @customer.token), class: 'button-pill') %>
                    <% end %>
                    <%= link_to('redigera', edit_customer_card_path(@customer.token, card.token), class: 'button-pill') unless card.sent_at %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    </div>


  </article>
</main>

<script>
  mixpanel.track("Show orders overview", {
    'user-email': '<%= @customer.donor.email %>',
    'user-type': '<%= @customer.donor.donor_type %>'
  });

  ga('send', 'event', 'order-overview', 'view', '<%= @customer.donor.donor_type %>');
</script>

<!-- Adform Tracking Code BEGIN -->
<script type="text/javascript">
    window._adftrack = Array.isArray(window._adftrack) ? window._adftrack : (window._adftrack ? [window._adftrack] : []);
    window._adftrack.push({
        pm: 563271,
        divider: encodeURIComponent('|'),
        pagename: encodeURIComponent('')
    });
    (function () { var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = 'https://track.adform.net/serving/scripts/trackpoint/async/'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); })();

</script>
<noscript>
    <p style="margin:0;padding:0;border:0;">
        <img src="https://track.adform.net/Serving/TrackPoint/?pm=563271&ADFPageName=&ADFdivider=|" width="1" height="1" alt="" />
    </p>
</noscript>
<!-- Adform Tracking Code END -->