config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'orders#new'

  get 'om',       to: 'pages#info', as: :info
  get 'hjalp',    to: 'pages#help', as: :help
  get 'integritetspolicy', to: 'pages#integritetspolicy', as: :integritetspolicy

  get 'dev-card', to: 'pages#dev_card', as: :dev_card
  get 'card-private-standard', to: 'pages#card_private_standard', as: :card_private_standard
  get 'card-private-xmas', to: 'pages#card_private_xmas', as: :card_private_xmas
  get 'card-business-standard', to: 'pages#card_business_standard', as: :card_business_standard
  get 'card-business-standard-en', to: 'pages#card_business_standard_en', as: :card_business_standard_en
  get 'card-business-xmas', to: 'pages#card_business_xmas', as: :card_business_xmas
  get 'dev-design', to: 'pages#dev_design', as: :dev_design

  get 'sms-order/jAuEhzn193', to: 'sms#new'
  get 'sms-order/s87sMxefrw', to: 'sms#new_xmas'
  get 'sms-order/Ksa812jDjb', to: 'sms#new_small'
  get 'sms-order/f12bnffG1A', to: 'sms#new_xmas_small'

  resources :giftcards

  get 'foretag2', to: 'giftcards#foretag'

  namespace :company, path: 'foretag' do
    get '/', to: 'orders#new'
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]
  end

  resources :persons, only: [:create]

  scope path_names: { new: 'skapa', edit: 'redigera' } do
    resources :cards, :digital_cards, :analog_cards, path: 'gavobevis', except: [:new] do
      get 'bekrafta', action: :confirmation, on: :member, as: :confirmation
      get 'forhandsgranska', action: :preview, on: :member, as: :preview
    end

    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]

    resource :cart, path: 'varukorg', only: [:show, :update]
    resource :checkout, path: 'checkout', path_names: { new: '' }, only: [:new] do
      get 'complete', action: :complete, as: :complete
      get 'swish', action: :swish, as: :swish
      post 'charge', action: :charge, as: :charge
      get 'swish_payment_status'
    end

    scope module: 'customer' do
      resources :customers, path: 'kund' do
        resources :cards, path: 'gavobevis', only: [:edit, :update] do
          get 'forhandsgranska', action: :preview, on: :member, as: :preview
        end
      end
    end
  end

  ##########################################
  # Service callbacks
  ##########################################
  scope '/callbacks' do
    post 'stripe', to: 'callbacks#stripe'
    post 'swish', to: 'callbacks#swish'
  end

  ##########################################
  # Sidekiq
  ##########################################
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_arg_jul.html.erb
<div class="arg-jul"><%= image_tag 'arg-jul.svg', data: { 'fallback': image_path('arg-jul.png') } %></div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="errors" id="errors">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </div>
<% end %>

app/views/shared/_extra_amount_form.html.erb
<%= form_for(OrderItem.new, url: controller_path == "company/orders" ? company_order_items_path : order_items_path) do |f| %>
  <%= f.hidden_field :order_id, value: @order.id %>
  <div class="add-item__content">
    <%= f.hidden_field :product_quantity, value: 1 %>
    <%= f.hidden_field :product, value: "Extra" %>
    <%= f.hidden_field :subtype, value: "extra" %>

      Extra gåva
      <%= f.number_field :quantity, min: Card::MINIMUM_QUANTITY, id: "new_bonus_amount", class: "add-item__input--quantity" %>
      kr

    <%= f.submit "Lägg till", class: "btn" %>
  </div>

<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "alert-box #{key} reveal-modal large", data: { alert: '' }) do %>
      <a href="#" class="close">&times;</a><p><%= value %></p>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row" style="font-size:0.8rem;">
      <div class="col-md-12">
        <ul class="nav" style="margin:0px;">
          <li class="nav-item">
            <%= link_to "Beställ som privatperson", root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Beställ som företag", company_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Gör så här", info_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Frågor och svar", help_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Tidigare beställningar", customers_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <span class="text-muted">Or­gan­i­sa­tion­snum­mer 802426-1268, Plus­giro 90 01 62-9, SWISH 900 16 29<br>
          Wa­t­erAid förän­drar liv genom rent vat­ten, san­itet och hy­gien | © Copy­right Wa­t­erAid<br>
          <a href="https://www.wateraid.org/se/regler-och-villkor" target="_blank">Regler och villkor</a> | <a href="https://www.wateraid.org/se/integritetspolicy" target="_blank">Integritetspolicy och cookies</a><br></br>
          <p><img src="/img/90konto.png" alt="Svensk Insamlingskontroll" /></p>

        </span>
      </div>
      <div class="col-md-6 text-right">
        <ul class="nav nav-footer-icons" style="float:right;margin:0px;">
          <li class="nav-item"><a href="https://www.facebook.com/wateraidswe/" class="nav-link" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a></li>
          <li class="nav-item"><a href="https://www.instagram.com/wateraidsweden/" class="nav-link" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
          <li class="nav-item"><a href="https://www.linkedin.com/company/wateraid-sverige/" class="nav-link" target="_blank"><i class="fab fa-linkedin fa-2x"></i></a></li>
          <li class="nav-item"><a href="https://www.twitter.com/wateraidsverige/" class="nav-link" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
          <li class="nav-item"><a href="https://www.youtube.com/wateraidsverige/" class="nav-link" target="_blank"><i class="fab fa-youtube fa-2x"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>


<div class="footer-tracking">
  <!-- Google Code for Remarketing Tag -->
  <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = <%= Rails.application.secrets.google_conversion_id %>;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
  </script>
  <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
  </script>
  <noscript>
    <div style="display:inline;">
      <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<%= Rails.application.secrets.google_conversion_id %>/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
  </noscript>

  <!-- Google Code for Remarketing Tag -->
  <script type="text/javascript">
  /* <![CDATA[ */
  var google_conversion_id = 950792424;
  var google_custom_params = window.google_tag_params;
  var google_remarketing_only = true;
  /* ]]> */
  </script>
  <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
  </script>
  <noscript>
  <div style="display:inline;">
  <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950792424/?value=0&amp;guid=ON&amp;script=0"/>
  </div>
  </noscript>

  <!-- Adform Tracking Code BEGIN -->
  <script type="text/javascript">
      var _adftrack = {
          pm: 307473,
          divider: encodeURIComponent('|'),
          pagename: encodeURIComponent('<%= content_for?(:title) ? yield(:title) + ' | WaterAid Gåvoshop' : 'WaterAid Gåvoshop' %>')
      };
      (function () { var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = 'https://track.adform.net/serving/scripts/trackpoint/async/'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); })();

  </script>
  <noscript>
      <p style="margin:0;padding:0;border:0;">
          <img src="https://track.adform.net/Serving/TrackPoint/?pm=307473&ADFPageName=<%= content_for?(:title) ? yield(:title) + ' | WaterAid Gåvoshop' : 'WaterAid Gåvoshop' %>&ADFdivider=|" width="1" height="1" alt="" />
      </p>
  </noscript>
  <!-- Adform Tracking Code END -->

  <script type="text/javascript">
  _linkedin_data_partner_id = "110236";
  </script><script type="text/javascript">
  (function(){var s = document.getElementsByTagName("script")[0];
  var b = document.createElement("script");
  b.type = "text/javascript";b.async = true;
  b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
  s.parentNode.insertBefore(b, s);})();
  </script>
  <noscript>
  <img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=110236&fmt=gif" />
  </noscript>

  <script type="text/javascript">
_linkedin_partner_id = "506449";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script><script type="text/javascript">
(function(){var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})();
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=506449&fmt=gif" />
</noscript>
</div>

<% if current_page?(root_path) %>
  <div class="modal-zoom-bg"></div>
<% end %>

app/views/shared/_footer_links.html.erb
<div class="footer-links">
  <%= link_to "Beställ som privatperson", root_path, class: 'button-pill' %>
  <%= link_to "Beställ som företag", company_path, class: 'button-pill' %>
</div>
<div class="footer-links">
  <%= link_to "Gör så här", info_path, class: 'button-pill' %>

  <%= link_to "Frågor och svar", help_path, class: 'button-pill' %>

  <%= link_to "Tidigare beställningar", customers_path, class: 'button-pill' %>
</div>
<div class="footer-links">
  <%= link_to "Till wateraid.se", 'http://www.wateraid.se', class: 'button-pill', :target => "_blank", :rel => "noopener"  %>
</div>

app/views/shared/_footer_registration.html.erb
<div class="footer-registration">
  <p>
    Organisationsnummer: 802426-1268 | Plusgiro: 90 01 62-9 | Bankgiro: BG 900-1629
  </p>
  <p>
    WaterAid förändrar liv genom vatten, sanitet och hygien | © Copyright WaterAid | <%= link_to "Integritetspolicy", integritetspolicy_path %>
  </p>
  <p>
    <img class="footer__90-logo" src="<%= image_url "90-logo.svg" %>" alt="WaterAid" data-fallback="<%= image_url "90-logo.png" %>">
  </p>
</div>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">
<title><%= content_for?(:title) ? yield(:title) + ' | WaterAid Gåvoshop' : 'WaterAid Gåvoshop' %></title>
<link rel="canonical" href="<%= request.original_url %>">

<meta property="fb:app_id" content="<%= Rails.application.secrets.facebook_app_id %>">
<meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'WaterAid Gåvoshop' %>">
<meta property="og:url" content="<%= request.original_url %>">
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : 'Beställ ett gåvobevis och ge bort rent vatten i present. En gåva som verkligen förändrar liv.' %>">
<meta property="og:image" content="<%= image_url 'og-logo-2016.jpg' %>">
<meta property="og:locale" content="sv_SE">
<meta property="og:site_name" content="WaterAid Gåvoshop">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<%= content_for?(:title) ? yield(:title) : 'WaterAid Gåvoshop' %>">
<meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : 'Beställ ett gåvobevis och ge bort rent vatten i present. En gåva som verkligen förändrar liv.' %>">
<meta name="twitter:image" content="<%= image_url 'og-logo-2016.jpg' %>">

<meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Beställ ett gåvobevis och ge bort rent vatten i present. En gåva som verkligen förändrar liv.' %>">

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <!-- Apple Touch Icons -->
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png" />
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
  <!-- Windows 8 Tile Icons -->
  <meta name="msapplication-square70x70logo" content="smalltile.png" />
  <meta name="msapplication-square150x150logo" content="mediumtile.png" />
  <meta name="msapplication-wide310x150logo" content="widetile.png" />
  <meta name="msapplication-square310x310logo" content="largetile.png" />



<%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "head" %>
  <!--[if lt IE 9]>
    <%= javascript_include_tag "ie" %>
  <![endif]-->
<%= csrf_meta_tags %>

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '770236689764961');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=770236689764961&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Rails.application.secrets.google_analytics_id %>', 'auto');
  ga('require', 'displayfeatures');
  ga('require', 'linkid', 'linkid.js');
  ga('require', 'ecommerce');
  ga('send', 'pageview');

</script>

app/views/shared/_head.pdf.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">
<title><%= content_for?(:title) ? yield(:title) + ' | WaterAid Gåvoshop' : 'WaterAid Gåvoshop' %></title>
<link rel="canonical" href="<%= request.original_url %>">

<meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Beställ ett gåvobevis och ge bort rent vatten i present. En gåva som verkligen förändrar liv.' %>">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

<%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "head" %>
  <!--[if lt IE 9]>
    <%= javascript_include_tag "ie" %>
  <![endif]-->
<%= csrf_meta_tags %>

app/views/shared/_header.html.erb
<header class="header" role="header">
	<!-- Logo -->
  <div class="row">
    <div class="header__logo small-12 columns">
      <a href="/">
        <img class="logo" src="<%= image_url "wateraid-logo.svg" %>" alt="WaterAid" data-fallback="<%= image_url "wateraid-logo.png" %>">
      </a>

      <div class="title">
        <h1>Gåvoshop</h1>
      </div>
    </div>
  </div><!-- END Logo -->
</header>
<!-- / .header -->

app/views/shared/_header_tracking.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= Rails.application.secrets.facebook_app_id %>',
      xfbml      : true,
      version    : 'v2.1'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/sv_SE/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<script>var seconds = 10;setTimeout(function() { fbq('track', 'ViewContent'); }, seconds * 1000);</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=770236689764961&amp;ev=ViewContent&noscript=1 " /></noscript>

<!-- Adwords -->
<!-- Global site tag (gtag.js) - AdWords: 827922118 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-827922118"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'AW-827922118');
</script>

<script>
  gtag('event', 'page_view', {
    'send_to': 'AW-827922118',
    'user_id': '1'
  });
</script>

<!-- Bing all pages -->
<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"41000043"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script>

app/views/shared/_receipt.erb
<div style="color: #ffffff; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; text-decoration: none; text-align:left;">

  <p>Hej <%= @order.donor.first_name %>!</p>

  <p>Ett stort tack för att du har valt att ge bort världens viktigaste present genom att beställa gåvobevis i vår gåvoshop. Snart kommer någons barn, förälder eller syskon för allra första gången få smaka rent vatten. Och det är tack vare dig!</p>

  <p>Har du beställt ett tryckt gåvobevis kommer det på posten inom fyra dagar. <br>Digitala gåvobevis skickas i ett separat e-mail till dig eller direkt till den du har valt att ge det till.</p>

  <p>Har du några frågor så kontakta oss på <a href="mailto:info@wateraid.se" style="color:#ffffff;text-decoration:underline;">info@wateraid.se</a> <br>eller ring 08-677 30 70.</p>

  <p>Allt börjar med vatten - tack för att du förändrar liv!</p>

  <p>
    Vänliga hälsningar,<br>
    Cecilia Chatterjee-Martinsen<br>
    Generalsekreterare, WaterAid
  </p>
</div>