config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'orders#new'

  get 'om',       to: 'pages#info', as: :info
  get 'hjalp',    to: 'pages#help', as: :help
  get 'integritetspolicy', to: 'pages#integritetspolicy', as: :integritetspolicy

  get 'dev-card', to: 'pages#dev_card', as: :dev_card
  get 'card-private-standard', to: 'pages#card_private_standard', as: :card_private_standard
  get 'card-private-xmas', to: 'pages#card_private_xmas', as: :card_private_xmas
  get 'card-business-standard', to: 'pages#card_business_standard', as: :card_business_standard
  get 'card-business-standard-en', to: 'pages#card_business_standard_en', as: :card_business_standard_en
  get 'card-business-xmas', to: 'pages#card_business_xmas', as: :card_business_xmas
  get 'dev-design', to: 'pages#dev_design', as: :dev_design

  get 'sms-order/jAuEhzn193', to: 'sms#new'
  get 'sms-order/s87sMxefrw', to: 'sms#new_xmas'
  get 'sms-order/Ksa812jDjb', to: 'sms#new_small'
  get 'sms-order/f12bnffG1A', to: 'sms#new_xmas_small'

  resources :giftcards

  get 'foretag2', to: 'giftcards#foretag'

  namespace :company, path: 'foretag' do
    get '/', to: 'orders#new'
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]
  end

  resources :persons, only: [:create]

  scope path_names: { new: 'skapa', edit: 'redigera' } do
    resources :cards, :digital_cards, :analog_cards, path: 'gavobevis', except: [:new] do
      get 'bekrafta', action: :confirmation, on: :member, as: :confirmation
      get 'forhandsgranska', action: :preview, on: :member, as: :preview
    end

    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]

    resource :cart, path: 'varukorg', only: [:show, :update]
    resource :checkout, path: 'checkout', path_names: { new: '' }, only: [:new] do
      get 'complete', action: :complete, as: :complete
      get 'swish', action: :swish, as: :swish
      post 'charge', action: :charge, as: :charge
      get 'swish_payment_status'
    end

    scope module: 'customer' do
      resources :customers, path: 'kund' do
        resources :cards, path: 'gavobevis', only: [:edit, :update] do
          get 'forhandsgranska', action: :preview, on: :member, as: :preview
        end
      end
    end
  end

  ##########################################
  # Service callbacks
  ##########################################
  scope '/callbacks' do
    post 'stripe', to: 'callbacks#stripe'
    post 'swish', to: 'callbacks#swish'
  end

  ##########################################
  # Sidekiq
  ##########################################
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/cart.rb
class Cart
  def initialize(session)
    @session = session
  end

  def add(card)
    order.cards << card
  end

  def remove(card)
    order.cards.destroy(card)
  end

  def destroy
    @order, @session[:cart_id] = nil

    true
  end

  def cards
    if cart_exists?
      order.cards
    else
      []
    end
  end

  def order
    @order ||= create_order
  end

  def empty?
    if cart_exists?
      cards.count > 0 ? false : true
    else
      true
    end
  end

  def find_card(token)
    Card.where(token: token, order_id: @session[:cart_id]).take!
  end

  private

  def create_order
    Order.find(@session[:cart_id])

    rescue ActiveRecord::RecordNotFound
      @order = Order.create!
      @session[:cart_id] = @order.id

      @order
  end

  def cart_exists?
    @session[:cart_id] ? true : false
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include NewCart
  before_action :current_cart

  def update
    if @order.update(order_params)
      @donor = @order.donor
      if @order.payment_type.eql?(Order::PAYMENT_TYPES[:card])
        if PurchaseOrderStripe.call(@order, @order.stripe_token)
          @order.order_items.each do |order_item|
            order_item.convert_to_cards
          end

          redirect_to complete_checkout_url
        else
          redirect_to company_path, flash: { notice: "Något gick fel med betalningen. Var vänlig att prova med ett annat betalkort." } if @donor.donor_type == :company
          redirect_to root_path, flash: { notice: "Något gick fel med betalningen. Var vänlig att prova med ett annat betalkort." }
        end
      elsif @order.payment_type.eql?(Order::PAYMENT_TYPES[:invoice])
        if PurchaseOrderInvoice.call(@order)
          @order.order_items.each do |order_item|
            order_item.convert_to_cards
          end

          redirect_to complete_checkout_url
        else
          redirect_to company_path if @donor.donor_type == :company
          redirect_to root_path
        end
      elsif @order.payment_type.eql?(Order::PAYMENT_TYPES[:swish])
        result = SwishService.perform(@order)
        if result.success?
          redirect_to swish_checkout_url
        else
          redirect_to company_path, flash: { notice: result.errors.to_s } if @donor.donor_type == :company
          redirect_to root_path, flash: { notice: result.errors.to_s }
        end
      end
    else
      error_message = @order.errors.full_messages.join(". ")

      if @order.donor.donor_type = "person"
        redirect_to root_path, flash: { notice: error_message }
      else
        redirect_to company_path, flash: { notice: error_message }
      end
    end
  end

  private
  def order_params
    params.require(:order).permit(
      :payment_type,
      :stripe_token,
      :swish_number,
      donor_attributes: [
        :donor_type, :first_name, :last_name, :company,
        :email, :org_number, :phone, :address, :post_code,
        :city, :country_code, :company_code
      ]
    )
  end
end

app/views/carts/_form.html.erb
<div class="cart-donor row" id="donor-info">
  <div class="medium-10 medium-push-1 column">
    <hr>
    <h2>Kontaktuppgifter</h2>

    <%= form_for @order, url: cart_path, :html => { :class => 'checkout' }, :data => {'parsley-validate' => '', 'rr-name' => 'checkout-form' } do |order_form| %>
      <%= order_form.hidden_field :stripe_token %>

      <div class="checkout">
        <%= order_form.fields_for :donor do |donor_form| %>
          <div class="form-item checkout__company">
            <%= donor_form.check_box :donor_type, {disabled: disabled}, 'company', 'person' %>
            <%= donor_form.label :donor_type, 'Vi är ett företag/organisation', class: 'label--inline' %>
          </div>

          <div class="checkout__company-fields row" id="checkout-company-info" style="width: 100% !important;">
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :company, 'Företagsnamn' %></h5>
              <%= donor_form.text_field :company, disabled: disabled, class: 'checkout__company-name' %>
            </div>

            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :org_number, 'Organisationsnummer' %></h5>
              <%= donor_form.text_field :org_number, disabled: disabled, class: 'checkout__company-orgnr' %>
            </div>
          </div>

          <div class="row">
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :first_name, 'Förnamn' %></h5>
              <%= donor_form.text_field :first_name, disabled: disabled, class: 'checkout__firstname', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt förnamn.'} %>
            </div>
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :last_name, 'Efternamn' %></h5>
              <%= donor_form.text_field :last_name, disabled: disabled, class: 'checkout__lastname', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt efternamn.'} %>
            </div>
          </div>

          <div class="row">
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :email, 'E-post' %></h5>
              <%= donor_form.email_field :email, disabled: disabled, class: 'checkout__email', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din e-postadress.', 'parsley-type-message' => 'Ange en giltig e-postadress.'} %>
            </div>
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :phone, 'Telefon' %></h5>
              <%= donor_form.text_field :phone, disabled: disabled, class: 'checkout__phone' %>
            </div>
          </div>

          <div class="form-item">
            <h5><%= donor_form.label :address, 'Adress' %></h5>
            <%= donor_form.text_field :address, disabled: disabled, class: 'checkout__adress', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din adress.'} %>
          </div>

          <div class="row">
            <div class="medium-4 column form-item">
              <h5><%= donor_form.label :post_code, 'Postnummer' %></h5>
              <%= donor_form.text_field :post_code, maxlength: 5, disabled: disabled, class: 'checkout__postal-code', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt postnr.', 'parsley-type' => 'integer', 'parsley-type-message' => 'Postnr får bara innehålla siffror', 'parsley-minlength' => '5', 'parsley-minlength-message' => 'Postnr måste innehålla minst 5 siffror'} %>
            </div>
            <div class="medium-8 column form-item">
              <h5><%= donor_form.label :city, 'Ort' %></h5>
              <%= donor_form.text_field :city, disabled: disabled, class: 'checkout__city', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din ort.'} %>
            </div>
          </div>

          <div class="row">
            <div class="medium-6 column form-item">
              <h5><%= donor_form.label :country_code, 'Land' %></h5>
              <%= donor_form.country_code_select :country_code, [[ 'Sverige', 'SE' ]], disabled: disabled, class: 'checkout__country' %>
            </div>
          </div>
        <% end %>

        <div class="checkout-payment form-item">
          <h5>Betala med</h5>

          <div class="checkout-payment-option">
            <%= order_form.radio_button :payment_type, :card, disabled: disabled, class: 'checkout__payment checkout__payment--card' %>
            <%= order_form.label :payment_type, 'Kort', value: :card, :class => 'label--inline' %>
          </div>

          <div class="checkout-payment-option">
            <%= order_form.radio_button :payment_type, :invoice, disabled: (!@order.invoicable? || disabled), :class => 'checkout__payment checkout__payment--invoice' %>
            <%= order_form.label :payment_type, 'Rekvisition', value: :invoice, class: 'label--inline' %>
          </div>
          <% unless @order.invoicable? %>
            <div class="t-meta">
              För att kunna betala mot rekvisition måste det totala ordervärdet överstiga <%= Order::INVOICABLE_MINIMUM %> kr.
            </div>
          <% end %>
        </div>

        <%= order_form.submit 'Fortsätt till kortbetalning', data: { email: donor.email, cards_count: donor.order.cards.count, amount: number_to_currency(donor.order.calculate_total) }, :class => 'checkout__submit-card', style: 'display: none;' %>
        <%= order_form.submit 'Genomför beställning', :class => 'checkout__submit-invoice', style: 'display: none;' %>

        <div class="checkout-stripe">
          <p class="checkout-stripe__info"><img src="<%= image_url "stripe-check.svg" %>" alt="" data-fallback="<%= image_url "stripe-check.png" %>"> Alla transaktioner krypteras för säker betalning.</p>
          <p class="checkout-stripe__logo"><img src="<%= image_url "stripe-logo.svg" %>" alt="Betalningen sker via Stripe" data-fallback="<%= image_url "stripe-logo.png" %>">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/carts/_form_error.erb
<div class="errors" id="errors">
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</div>

app/views/carts/_form_inputs.erb
<div class="checkout">
  <%= order_form.fields_for :donor do |donor_form| %>
    <div class="form-item checkout__company">
      <%= donor_form.check_box :donor_type, {disabled: disabled}, 'company', 'person' %>
      <%= donor_form.label :donor_type, 'Vi är ett företag/organisation', class: 'label--inline' %>
    </div>

    <div class="checkout__company-fields row" id="checkout-company-info">
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :company, 'Företagsnamn' %></h5>
        <%= donor_form.text_field :company, disabled: disabled, class: 'checkout__company-name', :data => {'parsley-required-message' => 'Ange företagets namn.'} %>
      </div>

      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :org_number, 'Organisationsnummer' %></h5>
        <%= donor_form.text_field :org_number, disabled: disabled, class: 'checkout__company-orgnr', :data => {'parsley-required-message' => 'Ange företagets orgnr.'} %>
      </div>
    </div>

    <div class="row">
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :first_name, 'Förnamn' %></h5>
        <%= donor_form.text_field :first_name, disabled: disabled, class: 'checkout__firstname', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt förnamn.'} %>
      </div>
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :last_name, 'Efternamn' %></h5>
        <%= donor_form.text_field :last_name, disabled: disabled, class: 'checkout__lastname', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt efternamn.'} %>
      </div>
    </div>

    <div class="row">
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :email, 'E-post' %></h5>
        <%= donor_form.email_field :email, disabled: disabled, class: 'checkout__email', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din e-postadress.'} %>
      </div>
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :phone, 'Telefon' %></h5>
        <%= donor_form.text_field :phone, disabled: disabled, class: 'checkout__phone' %>
      </div>
    </div>

    <div class="form-item">
      <h5><%= donor_form.label :address, 'Adress' %></h5>
      <%= donor_form.text_field :address, disabled: disabled, class: 'checkout__adress', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din adress.'} %>
    </div>

    <div class="row">
      <div class="medium-4 column form-item">
        <h5><%= donor_form.label :post_code, 'Postnummer' %></h5>
        <%= donor_form.text_field :post_code, disabled: disabled, class: 'checkout__postal-code', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange ditt postnr.'} %>
      </div>
      <div class="medium-8 column form-item">
        <h5><%= donor_form.label :city, 'Ort' %></h5>
        <%= donor_form.text_field :city, disabled: disabled, class: 'checkout__city', :data => {'parsley-required' => '', 'parsley-required-message' => 'Ange din ort.'} %>
      </div>
    </div>

    <div class="row">
      <div class="medium-6 column form-item">
        <h5><%= donor_form.label :country_code, 'Land' %></h5>
        <%= donor_form.country_code_select :country_code, [[ 'Sverige', 'SE' ]], disabled: disabled, class: 'checkout__country' %>
      </div>
    </div>
  <% end %>

  <div class="checkout-payment form-item">
    <h5>Betala med</h5>

    <div class="checkout-payment-option">
      <%= order_form.radio_button :payment_type, :card, disabled: disabled, class: 'checkout__payment checkout__payment--card' %>
      <%= order_form.label :payment_type, 'Kort', value: :card, :class => 'label--inline' %>
    </div>

    <div class="checkout-payment-option">
      <%= order_form.radio_button :payment_type, :invoice, disabled: (!@order.invoicable? || disabled), :class => 'checkout__payment checkout__payment--invoice' %>
      <%= order_form.label :payment_type, 'Rekvisition', value: :invoice, class: 'label--inline' %>
    </div>
    <% unless @order.invoicable? %>
      <div class="t-meta">
        För att kunna betala mot rekvisition måste det totala ordervärdet överstiga <%= number_with_delimiter(Order::INVOICABLE_MINIMUM, delimiter: ' ') %> kr.
      </div>
    <% end %>
  </div>

  <%= order_form.submit 'Fortsätt till kortbetalning', data: { email: donor.email, cards_count: donor.order.cards.count, amount: donor.order.calculate_total }, :class => 'checkout__submit-card', style: 'display: none;' %>
  <%= order_form.submit 'Genomför beställning', :class => 'checkout__submit-invoice', style: 'display: none;' %>
</div>

app/views/carts/_response_info.erb
<script>
  var handler = StripeCheckout.configure({
    key: '<%= Rails.application.secrets.stripe_publishable_key %>',
    name: 'WaterAid Gåvoshop',
    currency: 'SEK',
    allowRememberMe: false,
    image: '<%= image_path "wateraid-drop.png" %>',
    token: function(token) {
      req = $.post('<%= charge_checkout_path %>', { stripe_token: token.id });
      req.done(function(data) {
        window.location = '<%= complete_checkout_path %>';
      }),
      req.fail(function(data) {
        window.location = '<%= cart_url %>';
      })
    }
  });

  handler.open({
    email: '<%= order.donor.email %>',
    description: '<%= "#{order.cards.count} gåvobevis" %>',
    amount: <%= order.calculate_total * 100 %>,
    panelLabel: 'Betala'
  });
</script>

app/views/carts/checkout_card.html.erb
<h3> Betala med kort </h3>

<p>Fyll i dina betalkortuppgifter</p>

<form action="<%= checkout_path %>" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_4Tggao5rE3fJnM6Yxg3MQvrB"
    data-amount="2000"
    data-name="WaterAid Gåvoshop"
    data-currency="sek"
    data-description=""
    data-email = "<%= @order.donor.email %>"
    data-allow-remember-me = "false"
    <%# data-image="/128x128.png" %> >

  </script>
  <input type='hidden' name='order_id' value='<%= @order.id %>'>
</form>

app/views/carts/fail_action.js.erb
$('#errors').html('<%=j render "shared/error_messages", object: @order.donor %>');

app/views/carts/show.html.erb
<% title "Varukorg" %>
<% description "Dina gåvobevis" %>

<script src="https://checkout.stripe.com/checkout.js"></script>
<script type="text/javascript">
  var handler = StripeCheckout.configure({
    key: '<%= Rails.application.secrets.stripe_publishable_key %>',
    name: 'WaterAid Gåvoshop',
    currency: 'SEK',
    allowRememberMe: false,
    image: '<%= image_path "wateraid-drop.png" %>',
    token: function(token) {
      $('#order_stripe_token').val(token.id);
      $('form.checkout').submit();
    }
  });
</script>

<% if @cart.nil? || @cart.empty? %>
  <div class="row cart-empty">
    <div class="medium-10 medium-push-1 column">
      <h1>Varukorg</h1>
      <p class="t-meta">Din varukorg är tom. <br>Ge en gåva:</p>
      <p><%= link_to 'Privatpersoner', root_path, class: 'button'%> <%= link_to 'Företag', company_path, class: 'button'%></p>

      <hr>

      <h3>Vill du veta mer?</h3>
      <p><%= link_to 'Så fungerar det', info_path, class: 'button tiny'%> <%= link_to 'Frågor och svar', help_path, class: 'button tiny'%></p>
    </div>
  </div>

<% else %>
  <div class="cart row">
    <div class="medium-10 medium-push-1 column">
      <h1>Varukorg</h1>
      <hr>
      <h2>Gåvobevis</h2>

      <table class="order__items">
        <tr>
          <th>Typ</th>
          <th>Summa</th>
          <th></th>
        </tr>

        <% has_analog = false %>
        <% @cart.cards.order(created_at: :asc).each do |card| %>
          <% has_analog = true if card.type == 'AnalogCard' %>
          <% @donor.donor_type = :company if card.form_type == 'company' && @donor.new_record? %>
          <tr class="order__item">
            <td class="order__item__type">
              <%= card %>

              <% if card.type == 'DigitalCard' %>
                <small>
                  Gåvobeviset skickas

                  <% if card.send_at == Date.today %>
                    omgående
                  <% else %>
                    <%= card.send_at.strftime('%Y-%m-%d') %>
                  <% end %>

                  till

                  <% if card.send_to_donor == true %>
                    dig själv.
                  <% else %>
                    <%= card.receiver %>.
                  <% end %>
                </small>
              <% end %>
            </td>
            <td class="order__item__price"><%= card.price %> kr</td>
            <td class="order__item__actions">
              <% if card.type == 'DigitalCard' %>
                <%= link_to 'visa', preview_card_path(card.token), class: 'button-pill' %>
              <% end %>
              <%= link_to 'redigera', edit_card_path(card.token), class: 'button-pill' %>

              <% if card.type == 'DigitalCard' %>
                <%= link_to 'ta bort', card_path(card.token), class: 'button-pill', method: :delete, data: { confirm: "Vill du ta bort detta digitala gåvobevis för #{card.price} kr?" } %>
              <% else %>
                <%= link_to 'ta bort', card_path(card.token), class: 'button-pill', method: :delete, data: { confirm: "Vill du ta bort detta tryckta gåvobevis för #{card.price} kr?" } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>

      <% if has_analog %>
        <div class="cart__print-delivery">
          Tryckta kort skickas hem till dig inom fyra arbetsdagar.
        </div>
      <% end %>

      <div class="cart__total">
        <h5>Totalt <%= @order.calculate_total %> kr</h5>
      </div>

      <div class="cart__buy-more">
        <hr>
        <h2>Beställ fler gåvobevis</h2>
        <%= link_to 'Privatperson', root_path, class: 'button'%> <%= link_to 'Företag', company_path, class: 'button'%>
      </div>


    </div>
  </div>

  <%= render partial: 'form', locals: {donor: @donor, cart: @cart, disabled: false} %>
<% end %>

<div id='response-info'></div>

app/views/carts/update.js.erb
$('#donor-info').html('<%=j render(partial: 'form', locals: {donor: @donor, cart: @cart, disabled: true}) %>');
$('#response-info').html('<%=j render(partial: 'response_info', locals: {order: @order}) %>');