config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'orders#new'

  get 'om',       to: 'pages#info', as: :info
  get 'hjalp',    to: 'pages#help', as: :help
  get 'integritetspolicy', to: 'pages#integritetspolicy', as: :integritetspolicy

  get 'dev-card', to: 'pages#dev_card', as: :dev_card
  get 'card-private-standard', to: 'pages#card_private_standard', as: :card_private_standard
  get 'card-private-xmas', to: 'pages#card_private_xmas', as: :card_private_xmas
  get 'card-business-standard', to: 'pages#card_business_standard', as: :card_business_standard
  get 'card-business-standard-en', to: 'pages#card_business_standard_en', as: :card_business_standard_en
  get 'card-business-xmas', to: 'pages#card_business_xmas', as: :card_business_xmas
  get 'dev-design', to: 'pages#dev_design', as: :dev_design

  get 'sms-order/jAuEhzn193', to: 'sms#new'
  get 'sms-order/s87sMxefrw', to: 'sms#new_xmas'
  get 'sms-order/Ksa812jDjb', to: 'sms#new_small'
  get 'sms-order/f12bnffG1A', to: 'sms#new_xmas_small'

  resources :giftcards

  get 'foretag2', to: 'giftcards#foretag'

  namespace :company, path: 'foretag' do
    get '/', to: 'orders#new'
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]
  end

  resources :persons, only: [:create]

  scope path_names: { new: 'skapa', edit: 'redigera' } do
    resources :cards, :digital_cards, :analog_cards, path: 'gavobevis', except: [:new] do
      get 'bekrafta', action: :confirmation, on: :member, as: :confirmation
      get 'forhandsgranska', action: :preview, on: :member, as: :preview
    end

    resources :orders, only: [:show, :update]
    resources :order_items, only: [:create, :destroy]

    resource :cart, path: 'varukorg', only: [:show, :update]
    resource :checkout, path: 'checkout', path_names: { new: '' }, only: [:new] do
      get 'complete', action: :complete, as: :complete
      get 'swish', action: :swish, as: :swish
      post 'charge', action: :charge, as: :charge
      get 'swish_payment_status'
    end

    scope module: 'customer' do
      resources :customers, path: 'kund' do
        resources :cards, path: 'gavobevis', only: [:edit, :update] do
          get 'forhandsgranska', action: :preview, on: :member, as: :preview
        end
      end
    end
  end

  ##########################################
  # Service callbacks
  ##########################################
  scope '/callbacks' do
    post 'stripe', to: 'callbacks#stripe'
    post 'swish', to: 'callbacks#swish'
  end

  ##########################################
  # Sidekiq
  ##########################################
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/giftcard.rb
class Giftcard < ActiveRecord::Base  
    mount_uploader :thumbnail, ImageUploader
    mount_uploader :preview_swedish, ImageUploader
    mount_uploader :preview_english, ImageUploader
end

app/controllers/giftcards_controller.rb
class GiftcardsController < InheritedResources::Base

  def foretag
    @giftcards = Giftcard.where(:in_which_store => 'foretag')
  end

  private

    def giftcard_params
      params.require(:giftcard).permit(:name, :description, :category, :in_which_store, :amount)
    end
end

app/helpers/giftcards_helper.rb
module GiftcardsHelper
end

app/views/giftcards/_form.html.erb
<%= semantic_form_for @giftcard do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :category %>
    <%= f.input :in_which_store %>
    <%= f.input :amount %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/giftcards/edit.html.erb
<h1>Editing Giftcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @giftcard %> |
<%= link_to 'Back', giftcards_path %>

app/views/giftcards/foretag.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <% @giftcards.each do |giftcard| %>
  <div class="col-md-3">
    <div class="card">
      <img class="card-img-top" src="/img/card-placeholder.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title" style="color:#00adb8;"><%= giftcard.amount %> kronor</h5>
        <p class="card-text"><%= giftcard.description %></p>
        <div class="text-right">
          <%= link_to 'Beställ', giftcard, :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/giftcards/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <% @giftcards.each do |giftcard| %>
  <div class="col-md-3">
    <div class="card">
      <img class="card-img-top" src="/img/card-placeholder.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title" style="color:#00adb8;"><%= giftcard.amount %> kronor</h5>
        <p class="card-text"><%= giftcard.description %></p>
        <div class="text-right">
          <%= link_to 'Beställ', giftcard, :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/giftcards/list.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Giftcards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>In which store</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @giftcards.each do |giftcard| %>
      <tr>
        <td><%= giftcard.name %></td>
        <td><%= giftcard.description %></td>
        <td><%= giftcard.category %></td>
        <td><%= giftcard.in_which_store %></td>
        <td><%= giftcard.amount %></td>
        <td><%= link_to 'Show', giftcard %></td>
        <td><%= link_to 'Edit', edit_giftcard_path(giftcard) %></td>
        <td><%= link_to 'Destroy', giftcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Giftcard', new_giftcard_path %>

app/views/giftcards/new.html.erb
<h1>New Giftcard</h1>

<%= render 'form' %>

<%= link_to 'Back', giftcards_path %>

app/views/giftcards/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <img class="card-img-top" src="/img/card-placeholder.jpg" alt="Card image cap">
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title" style=""><%=@giftcard.amount %> kronor</h5>
        <p class="card-text"><%=@giftcard.description %></p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card bg-white">
      <div class="card-body">
        <p>Väljer mellan digitalt eller tryckt kort:</p>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="card_type" value="digital" ng-checked="true">
          <label class="form-check-label" for="digitalCard">
            Digitalt kort
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="card_type" value="print">
          <label class="form-check-label" for="printCard">
            Tryckt kort (+30 kr)
          </label>
        </div>
        <br />
        <button ng-click="add_to_cart(card);" class="btn btn-primary btn-block btn-lg">Beställ</button>

      </div>

    </div>
  </div>
</div>




<%= link_to 'Edit', edit_giftcard_path(@giftcard) %> |
<%= link_to 'Back', giftcards_path %>